name: pressure_monitor_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_size_and_fade: ^3.0.1
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  http: ^1.1.0
  ionicons: ^0.2.2
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.1.6
  fl_chart: ^0.66.1
  pdf: ^3.10.7
  path_provider: ^2.1.2
  permission_handler: ^11.2.1
  open_file: ^3.3.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/
    - lib/.env